# Generated by Django 4.0 on 2022-01-12 18:18

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersapp", "0003_alter_user_uuid"),
        ("tasksapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("3f8344dc-d9bd-42de-b454-31448cc7122d"), primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="created_by",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="usersapp.user"),
        ),
        migrations.AlterField(
            model_name="todo",
            name="project",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tasksapp.project"),
        ),
        migrations.AlterField(
            model_name="todo",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("ced2f606-4ac4-462d-8f20-2d2f0f41b35b"), primary_key=True, serialize=False
            ),
        ),
    ]
