# Generated by Django 4.0 on 2022-01-12 18:38

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasksapp", "0002_alter_project_uuid_alter_todo_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="todo",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
