# Generated by Django 4.0 on 2022-01-12 18:18

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersapp", "0002_alter_user_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("73d3bc26-1ee4-4071-8f30-35b4a4e54fb2"), primary_key=True, serialize=False
            ),
        ),
    ]
